name: app

type: php:8.2

build:
    flavor: composer

dependencies:
    php:
        composer/composer: '^2'

relationships:
    database: "database:mysql"

web:
    locations:
        "/":
            root: "appractic.so/public"
            index:
                - index.php
            scripts:
                - auto_prepend_file: null
            allow: true
            passthru: "/index.php"

disk: 2048

mounts:
    'appractic.so/storage/app/public':
        source: local
        source_path: 'public'
    'appractic.so/storage/framework/views':
        source: local
        source_path: 'views'
    'appractic.so/storage/framework/sessions':
        source: local
        source_path: 'sessions'
    'appractic.so/storage/framework/cache':
        source: local
        source_path: 'cache'
    'appractic.so/storage/logs':
        source: local
        source_path: 'logs'
    'appractic.so/bootstrap/cache':
        source: local
        source_path: 'cache'

hooks:
    build: |
        set -e
        cd appractic.so
        composer install --no-dev --prefer-dist --optimize-autoloader
        php artisan optimize:clear
        php artisan optimize
    deploy: |
        cd appractic.so
        php artisan migrate --force
